export const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 15.99,
    category: "Fiction",
    rating: 4,
    tags: ["bestselling", "popular"],
    cover: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    price: 12.49,
    category: "Science Fiction",
    rating: 5,
    tags: ["new", "popular"],
    cover: "https://covers.openlibrary.org/b/id/7222161-L.jpg",
  },
  {
    id: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 14.95,
    category: "Classic",
    rating: 4,
    tags: ["bestselling", "new"],
    cover: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
  },
  {
    id: 4,
    title: "Atomic Habits",
    author: "James Clear",
    price: 17.95,
    category: "Self-Help",
    rating: 5,
    tags: ["bestselling", "popular"],
    cover: "https://covers.openlibrary.org/b/id/10280349-L.jpg",
  },
  {
    id: 5,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 18.99,
    category: "Non-Fiction",
    rating: 5,
    tags: ["popular"],
    cover: "https://covers.openlibrary.org/b/id/8370224-L.jpg",
  },
  {
    id: 6,
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    price: 9.99,
    category: "Children",
    rating: 4,
    tags: ["new"],
    cover: "https://covers.openlibrary.org/b/id/8228781-L.jpg",
  },
  {
    id: 7,
    title: "It Ends With Us",
    author: "Colleen Hoover",
    price: 13.49,
    category: "Romance",
    rating: 4,
    tags: ["bestselling", "new"],
    cover: "https://covers.openlibrary.org/b/id/12518298-L.jpg",
  },
   {
    id: 9,
    title: "It Ends With Us",
    author: "Colleen Hoover",
    price: 13.49,
    category: "Romance",
    rating: 4,
    tags: [ "new"],
    cover: "https://covers.openlibrary.org/b/id/12518298-L.jpg",
  },
  {
    id: 8,
    title: "Educated",
    author: "Tara Westover",
    price: 16.95,
    category: "Biography",
    rating: 4,
    tags: ["popular", "bestselling"],
    cover: "https://covers.openlibrary.org/b/id/8897191-L.jpg",
  },
];
